baseURL = "https://suriyasonphu.com"
languageCode = "en"
title = "TECHFOR by suriyasonphu"
theme = "PaperMod"

enableRobotsTXT = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

# PaperMod specific configurations
paginate = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  description = "A blog about technology and knowledge sharing by Suriya Sonphu | บล็อกนี้ใช้สำหรับแบ่งปันความรู้ทั่วไปที่เกิดจากการอ่านและศึกษาอย่างไม่สิ้นสุด หมวดหมู่พัฒนาตนเอง จิตวิทยา เทคโนโลยี การเขียนโปรแกรม"
  keywords = ["สุริยา สนภู่", "suriyasonphu", "Suriya Sonphu" ,"blog", "technology", "programming", "dailylife", "reading"]
  author = "Suriya Sonphu"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    favicon = "/assets/favicon/favicon.ico"
    favicon16x16 = "/assets/favicon/favicon-16x16.png"
    favicon32x32 = "/assets/favicon/favicon-32x32.png"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "stay-reading"
    name = "Stay Reading"
    url = "/categories/stay-reading/"
    weight = 50
  
  [[menu.main]]
    identifier = "technologies"
    name = "Technology"
    url = "/categories/technology/"
    weight = 40
  

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
