baseURL = "https://suriyasonphu.com"
languageCode = "en"
title = "TECHFOR by suriyasonphu"
theme = "PaperMod"

# PaperMod specific configurations
Pagination.paperSize = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "TECHFOR by suriyasonphu"
  description = "A blog about technology and knowledge sharing"
  keywords = ["blog", "technology", "programming", "Dailylife"]
  author = "Suriya Sonphu"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
